### ISSUE TITLE
crash, unsure of origin

### ISSUE THREAD

**Issue by xemnes** [baileydel/VillagerMarkers-1.12.2#1]
running into a crash in villages with this mod
https://pastes.dev/bm2I0kHsNY

there doesnt appear to much info of whats causing it

**Comment by baileydel** [comment]
seems to be caused by mcp.mobius.waila.addons.minecraft.HUDHandlerVillager, when it's trying to access the nbt data of a villager, but cannot find the field careerId using ReflectionHelper. Villager Markers doesn't change the field careerId in anyway. Can you ensure that your modpack works without Villager Markers?

**Comment by xemnes** [comment]
huh, seems youre correct. sorry about that lol. i wonder whats causing it then, it wasnt happening before. unless its lolisasm, will have to check.
